name: Node.js CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run ESLint
      - name: Run Lint
        run: npm run lint

      # Run test cases
      - name: Run Tests
        run: npm test

      # Security vulnerability scan
      - name: Security Scan
        run: npm audit --audit-level=high

      # SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=devops-traveller_login-api-ci-project
            -Dsonar.organization=devops-traveller
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}